### PR TITLE
pp and permid from scratch

### PR DESCRIPTION
**Pull request by davidfarmer**
Redid the prettyprinting and permids from a fresh clone.

### CODE REVIEW

**Comment by rbeezer** [comment]
Sounds to me like we need to be more careful about what PG output looks like.

If the XSL (used in the step that constructs this) eventually imports 
mathbook-common.xsl  then a lot of "inter-element" whitespace is ignored in the 
early going.

I'm going to guess that the webwork extraction XSL needs a serious look.  I 
guess it is possible that some of the low-level templates in mathbook-common are 
not being applied due to variances like using "value-of" versus 
"apply-templates", etc.

Try having suspect templates output begin/end text markers to isolate who/which 
is responsible for the whitespace.

**Comment by Alex-Jordan** [comment]
@rbeezer, OK, I will look at WW XSL like this as part of the upcoming work on answers (which is still waiting release of 2.14).

But I found a similar thing with an introduced space that is not about a WW. The original PTX source (before pretty-print) is:
```
        <example>
            <title>The Alternate Definition of Absolute Value: <m>\abs{x}=\sqrt{x^2}</m></title>
            <statement>
                <p>Simplify the following expressions using the fact that <m>\abs{x}=\sqrt{x^2}</m>.<ol label="a." cols="2">
                    <li><p><m>\sqrt{x^{14}}</m></p></li>
```

After pretty-print, the important thing is where the `ol` lands:
```
    <example permid="yFd">
      <title>The Alternate Definition of Absolute Value: <m>\abs{x}=\sqrt{x^2}</m></title>
      <statement>
        <p permid="ejJ">
          Simplify the following expressions using the fact that <m>\abs{x}=\sqrt{x^2}</m>.

          <ol label="a." cols="2" permid="jKA">
            <li permid="Zlv">
              <p permid="pen">
                <m>\sqrt{x^{14}}</m>
              </p>
            </li>
```

Now the output HTML has the "before" version with this HTML p:
```
<p>Simplify the following expressions using the fact that \(\abs{x}=\sqrt{x^2}\text{.}\)</p>
```

And the "after" version with an extra space at the end of the p:
```
<p>Simplify the following expressions using the fact that \(\abs{x}=\sqrt{x^2}\text{.}\) </p>
```

I am not saying this is a problem, but maybe? I just want to report what I am seeing from the before-after diff.

**Comment by rbeezer** [comment]
I'll need to closely at how we bust up a PTX "p" into a sequence of HTML "p", 
"ol", "me", etc.

Would you mind copying this onto the "mathbook" repo as an issue, so everybody 
there sees it?  Thanks.

**Comment by Alex-Jordan** [comment]
Here is another one.

Source before PP:
```
                <p>The <url href="https://en.wikipedia.org/wiki/Five_hundred_meter_Aperture_Spherical_Telescope">Five-hundred-meter Aperture Spherical Telescope</url><fn><url href="https://en.wikipedia.org/wiki/Five_hundred_meter_Aperture_Spherical_Telescope">en.wikipedia.org/wiki/Five<underscore/>hundred<underscore/>meter<underscore/>Aperture<underscore/>Spherical<underscore/>Telescope</url></fn> (<acro>FAST</acro>) located in SW China is the worlds largest radio telescope. The name is actually incorrect because it is not spherical: it is parabolic! Parabolic telescopic dishes are very common because parabolas have the unique feature that they focus light coming in at a single point where a collecting instrument is placed.</p>
```

After PP:
```
        <p permid="Ola">
          The <url href="https://en.wikipedia.org/wiki/Five_hundred_meter_Aperture_Spherical_Telescope">Five-hundred-meter Aperture Spherical Telescope</url><fn>
          <url href="https://en.wikipedia.org/wiki/Five_hundred_meter_Aperture_Spherical_Telescope">en.wikipedia.org/wiki/Five<underscore/>hundred<underscore/>meter<underscore/>Aperture<underscore/>Spherical<underscore/>Telescope</url>
          </fn>(<acro>FAST</acro>) located in SW China is the worlds largest radio telescope.
          The name is actually incorrect because it is not spherical:
          it is parabolic!
          Parabolic telescopic dishes are very common because parabolas have the unique feature that they focus light coming in at a single point where a collecting instrument is placed.
        </p>
```

This time, an important space character in the HTML goes away. It's the one before the open paren surrounding the FAST acronym. HTML before:
```
<p>The <a class="url" target="_blank">Five-hundred-meter Aperture Spherical Telescope</a><a knowl="" class="id-ref" ><sup> 1 </sup></a><span class="hidden-content tex2jax_ignore"><span class="footnote"><a class="url" target="_blank">en.wikipedia.org/wiki/Five_hundred_meter_Aperture_Spherical_Telescope</a></span></span> (<abbr class="acronym">FAST</abbr>) located in SW China is the worlds largest radio telescope. The name is actually incorrect because it is not spherical: it is parabolic! Parabolic telescopic dishes are very common because parabolas have the unique feature that they focus light coming in at a single point where a collecting instrument is placed.</p>
```

HTML after:
```
<p>The <a class="url" target="_blank">Five-hundred-meter Aperture Spherical Telescope</a><a knowl="" class="id-ref" ><sup> 1 </sup></a><span class="hidden-content tex2jax_ignore"><span class="footnote"><a class="url" target="_blank">en.wikipedia.org/wiki/Five_hundred_meter_Aperture_Spherical_Telescope</a></span></span>(<abbr class="acronym">FAST</abbr>) located in SW China is the worlds largest radio telescope. The name is actually incorrect because it is not spherical: it is parabolic! Parabolic telescopic dishes are very common because parabolas have the unique feature that they focus light coming in at a single point where a collecting instrument is placed.</p>
```

At first glance, this appears to be a pretty-print issue with how it handles `fn`.

**Comment by Alex-Jordan** [comment]
I set out to compare HTML output before and after the pretty-print and permid application. I have examined more than 99% of the diff lines, deleting common patterns as I go. I am satisfied that the last 1200 lines or so are probably all good things to change. I have documented (here and at #971, #972) some other space issues that are probably not about the pretty-print. The one I'm unsure of is this last one I posted involving the footnote. 

So either
1. That is a pretty-print issue and it can be fixed and pp reapplied to ORCCA and I can merge. Or
2. That is a pretty-print issue and it can be fixed later and I can merge now. Or
3. It's not a pretty-print issue and I can merge now.

I'll wait to hear from David and/or Rob about it.

**Comment by davidfarmer** [comment]
I was a bit iffy about how to handle prettyprinting of footnotes,
and I see here that I need to be careful about the white space after
the closing "fn" tag.

Probably I can fix this.  I'll ask if I have any questions.

David

**Comment by Alex-Jordan** [comment]
The pretty print turned
```
        <p>A <term>ratio</term><idx><h>ratio</h></idx> is a means of comparing two quantities using division. One common example is a unit price. For example, if a box of cereal costs <m>\$3.99</m> and weighs <m>21</m> ounces then we can write this ratio as:
            <me>\frac{\$3.99}{21\,\text{oz}}</me>

        If we want to know the unit price (that is, how much each individual ounce costs), then we can divide <m>\$3.99</m> by <m>21</m> ounces<!-- <quantity><mag>21</mag><unit base="foot"/></quantity> --> and obtain <m>\$0.19</m> per ounce. These two ratios, <m>\frac{\$3.99}{21\,\text{oz}}</m> and <m>0.19\frac{\$}{\text{oz}}</m> are equivalent, and the equation showing that they are equal is a <term>proportion</term><idx><h>proportion</h></idx>. In this case, we could write the following proportion:
            <me>\frac{\$3.99}{21\,\text{oz}}=\frac{\$0.19}{1\,\text{oz}}</me>

        In this section, we will extend this concept and write proportions where one quantity is unknown and solve for that unknown.</p>
```
into
```
    <p permid="Gpy">
      A <term>ratio</term>
          <idx><h>ratio</h></idx>
      is a means of comparing two quantities using division.
      One common example is a unit price.
      For example,
      if a box of cereal costs <m>\$3.99</m> and weighs <m>21</m> ounces then we can write this ratio as:
      <me permid="vQt">
        \frac{\$3.99}{21\,\text{oz}}
      </me>
      If we want to know the unit price
      (that is, how much each individual ounce costs),
      then we can divide <m>\$3.99</m> by <m>21</m> ounces<!-- <quantity><mag>21</mag><unit base="foot"/></quantity> -->and obtain <m>\$0.19</m> per ounce.
      These two ratios,
      <m>\frac{\$3.99}{21\,\text{oz}}</m> and <m>0.19\frac{\$}{\text{oz}}</m> are equivalent,
      and the equation showing that they are equal is a <term>proportion</term>.
          <idx><h>proportion</h></idx>
      In this case, we could write the following proportion:
      <me permid="bXC">
        \frac{\$3.99}{21\,\text{oz}}=\frac{\$0.19}{1\,\text{oz}}
      </me>
      In this section,
      we will extend this concept and write proportions where one quantity is unknown and solve for that unknown.
    </p>
```
In the middle of all that, there is a comment right after an `ounces` and before an `and`. Because of how the pretty print removed the spaces around the comment, it comes out as `ouncesand`.

**Comment by Alex-Jordan** [comment]
The pretty print turned
```
                Before we can just eliminate the units, we'll need to convert <quantity><mag>5</mag><unit base="foot"/></quantity> <quantity><mag>6</mag><unit base="inch"/></quantity> to feet:
```
into
```
          Before we can just eliminate the units, we'll need to convert
          <quantity>
            <mag>5</mag><unit base="foot"/>
          </quantity><quantity>
            <mag>6</mag><unit base="inch"/>
          </quantity>
          to feet:
```
And in the output, there is no space between the two quantities: 
```
<p>Before we can just eliminate the units, we'll need to convert 5 ft6 in to feet:</p>
```

**Comment by rbeezer** [comment]
Dear Alex and David,

@davidfarmer - thanks for the  `fn`  and   `quantity`  fixes.

I've been struggling with this one all week.  I think I now understand the empty `p` problem and then have a fix.  I have not even begun to think about the spaces after periods at the end of sentences.

Anyway, just reporting that I've had this as a priority and will keep at it.

I will report/discuss on the PreTeXt lists.

@Alex-Jordan - could you keep track of progress here, and close once satisfied?  (No big rush.)  I'd rather just keep my work on the PreTeXt side.  Thanks very much for reporting these, it'll tighten up a lot of low-level code.  Even if it makes my head hurt.  ;-)

**Comment by Alex-Jordan** [comment]
Thanks David. I merged and then visited all the comments that came out like `\w<!--` and manually changed them as needed.

There is still the issue with a close `quantity` and open `quantity` coming out adjacent, like `</quantity><quantity>`. Elsewhere, an open quantity seems to come out on a new line. I believe that if this open `quantity` would also come out on its own line, then things like "5 ft6 in" would come out as "5 ft 6 in".

I manually changed the instances of this.

**Comment by rbeezer** [comment]
I think "quantity" should be a container (ie strip-space in XSL-speak).  Watch 
the PTX issue.

**Comment by Alex-Jordan** [comment]
I thought more about this, and now I think that there should be an `nbsp` in between the two quantities anyway.

**Comment by Alex-Jordan** [comment]
And thinking even more about this, logically "5 ft 6 in" is a single quantity. Maybe the markup should allow for that within one `quantity`. For now I will just go with `nbsp`.

**Pull request merged**
