### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by aecary**

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Can you delete the previous versions of these files at the same time? 
`git rm chapter-quadratic-equations.ptx`
`git rm chapter-quadratic-functions.ptx`

Then `git add ...` and commit.

For next time, if these were all in one commit, git would recognize that essentially a file was renamed, and that would be reflected in the diff. Helpful when the file has more content and history, but doesn't really matter here.

Also
`mv chapter-quadratic-equations.ptx chapter-solving-quadratic-equations.ptx` 
is the command line way to "move" (rename) a file.

**Comment by aecary** [comment]
Yes, I can do that. 

Thanks, that's helpful.

**Comment by aecary** [comment]
I got:
fatal: pathspec 'chapter-quadratic-equations.ptx' did not match any files

**Comment by aecary** [comment]
I renamed them locally, which was probably not the route to go. Should I go into git and delete them instead?

**Comment by Alex-Jordan** [comment]
GitHub is only showing that two files were added and the hub file had the references changed. It's not showing that two files were removed at the same time (and it is not indicating to me that two files were replaced either).

What do you get with `git status` right now? And with `ls`? (while in the `src` folder).

**Comment by aecary** [comment]
git status shows the file I'm working on now, and two with things commented
out for that work:

modified:   src/backmatter.ptx
    modified:   src/orcca.ptx
    modified:   src/section-graphing-quadratic-functions.ptx

I don't quite know how to do that last part... I assume I type ls and then
something?


*Ann Cary*
(she/her pronouns)
Mathematics Instructor
Curriculum Committee Chair
Portland Community College
Sylvania Campus, ST 203
971-722-7590
<http://goog_233805033>
http://spot.pcc.edu/~acary/

**Comment by Alex-Jordan** [comment]
Oh, I mean type `ls` while in the `src` folder. It lists the files there. We're looking see if the old files are still there.

**Comment by Alex-Jordan** [comment]
When you did `git rm` before, were you in the `src` folder? If you were up in `orcca` instead, it would explain the message you got that it didn't find such files.

**Comment by aecary** [comment]
Yes, that was the issue.

So for "git add ..." do I add "chapter-quadratic-equations.ptx", right? And then similar for the other file.

**Comment by Alex-Jordan** [comment]
Looks good. (I went out with H on some errands.)

**Pull request merged**
