### PR TITLE
Suggestion/comment to add explaination/example

### PR DESCRIPTION
**Pull request by iankitnicolas**
I did not include the graphically solution since we have not yet figured out how to make "make images" work for my setup. But the graphical solution and figure is commented out in the example that I added so we can just include it quickly once we get it sorted.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Thanks Ian, a few notes:

* If we use `<!-- TODO: ... -->` that at least one benefit over `<!-- to-do: ... -->`. I am in the habit of searching for "TODO" to find these, so it would just help me not miss them to stay with that standard. Also I think that PTX itself has a way to process comments with "TODO:" in them to generate a list of such items. (Although maybe it is written to catch "to-do:" as well, not sure.)
* I think that Kara is looking for more with this example. An explicit discussion with the student of how to think about "4 < x". Something that says when the variable is on the right, you may find it helpful to write it in reverse like "x > 4" before you try to visualize it or write interval notation.

If you make further edits to the file, you can commit them and push to your GH account, and this pull request will automatically reflect that.

**Comment by iankitnicolas** [comment]
Thanks for the comments Alex,

Here is a summary of what I added:
- Changed "To-do" to "TODO"
- Added an explanation to show that "4 < x" is equivalent to "x > 4"
- Also included a few more examples of "flipping" inequalities, such as "z <= 0 is equivalent to 0>=z", etc.
- Included warning to readers not to confuse "flipping" inequalities with changing comparison symbol direction when multiplying or dividing by neg. numbers

I tried my best to balance explaining things thoroughly and succinctly without being too verbose, but let me know if I am leaning too close to one or another. I also tried my best to match the "writing style" to the other examples so it didn't read too much like a different voice. I know we didn't really talk about this, but I assume this is what you want for readers.

Also, is there a better term for "flipping"? I did not want to use "changing direction" since it is already used in the main fact of the section...but I could not think of a better one.

**Comment by Alex-Jordan** [comment]
Thanks, getting closer. Just one thing to change I think.

* Don't worry more than the basics about consistent style. It's sort of how OER goes, by nature, with multiple contributors. Personally I don't think consistent style would have an impact on student success. It's sort of a cosmetic luxury (imho).
* With quotes, don't put them directly into source. There is a `q` tag, because different systems will do different things with "smart quotes" that are angled. So instead of `"<m>4</m> is less than <m>x</m>"`, you would have `<q><m>4</m> is less than <m>x</m></q>`. And the same for `"flipping"`.
* All I can think of as an alternative to "flipping" is "reversing the direction of...". I don't have a preference.

Are you comfortable with editing again to do the quotes, and putting that on its own commit separate from any other open work you may have right now? Holler if not and I can take care of the quotes.

**Comment by iankitnicolas** [comment]
Thanks for the feedback Alex!

I think I have gotten used to the whole process now. Hopefully I only pushed to changes I made to the relevant file. I did make changes to other files that I worked on in the mean time, but I think I only committed and pushed the one file.

**Pull request merged**
