### PR TITLE
changed examples so that the constants and solutions are more varied

### PR DESCRIPTION
**Pull request by aecary**
Carl: These are the changes to the examples that we discussed. Please review them. I think that one more example with a non-integer solution is now needed; let me know your thoughts.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
```
<mrow>\highlight{{} 2}\cdot\left(\frac{1}{2}x\right)\amp=\highlight{{} 2}\cdot(10)</mrow>
```

is not quite ideal. There is no need for the extra `{}` inside the highlight to the left of the `2`. However, since the `\cdot` is part of the new step, it should be highlighted. And then, since `\cdot` is a binary operator, an extra brace pair on its right will provide adequate spacing. Without this, the closing brace for the `\highlight` command will prevent the `\cdot` from "seeing" its right operand.

```
<mrow>\highlight{2\cdot{}}\left(\frac{1}{2}x\right)\amp=\highlight{2\cdot{}}10</mrow>
```

There is perhaps a way to package this into a macro, so we don't have to think about it. Ann suggested this in a forum post.

**Comment by Alex-Jordan** [comment]
If Ann wants to act on my last comment, she could make edits, make another commit, and push before Carl merges the PR.

If Carl wants to act on my last comment, he could merge the PR and then immediately make edits, and make another commit.

**Comment by aecary** [comment]
I'll make those changes. There are a few others later that need to be edited as well.

**Comment by Alex-Jordan** [comment]
Still a few places like this: `\highlight{{}12\cdot}`

That should be like: `\highlight{12\cdot{}}`

**Comment by aecary** [comment]
Oh now I see. I noticed that there were things appearing differently but could not catch what was typeset differently.

**Comment by aecary** [comment]
Carl: It should be ready for you to review now.

**Pull request merged**
