### PR TITLE
Update section-combining-like-terms.ptx

### PR DESCRIPTION
**Pull request by karashanecolley**
I added in 3 challenge problems from ORCCA edition 1.  They were in ORCCA edition 1, section 1.2 on fractions.  They aren't anywhere in ORCCA edition 2.  I thought they fit best in "Combining Like terms."

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Thanks Kara, I'll look this over and probably merge soon.

I think these are in edition 2. We put most of the original chapter 1 into appendix A. I see three challenge problems at the end of appendix A here:
https://spot.pcc.edu/math/orcca/ed2/html/section-fractions-and-fraction-arithmetic.html

**Comment by karashanecolley** [comment]
Oh....okay.  Sorry about that.  I didn't know they were in the Appendix.
You can leave them there.




*Kara Colley-Math Instructor at PCC Rock Creek*
*-*
*Coordinator for Portland Math Teachers' Circle*

**Comment by Alex-Jordan** [comment]
We should take a look. If they are good for where you added them, let's put them there. Maybe both places.

**Comment by Alex-Jordan** [comment]
Hi Kara, the section has evolved its structure so much that I have to close this pull request. But I did put the three problems at the end of this section as challenge problems for edition 3.

**Pull request closed without merging**
