### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by aecary**

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
I just merged this PR, but now I wish I had looked more carefully. It has a lot of edits to `section-solving-quadratic-equations-by-using-a-square-root.ptx` which is in chapter 8. I've also made a lot of edits to this one in my review yesterday and today, and there are 4 conflicts. Worse, I rearranged things in this section more than usual, and it looks like you did some of that too from the diff. So even beyond the 4 conflicts, the reading flow may be messed up if I just narrowly address the conflicts. 

Would you take a look at the diff for this file in this pull request, and see if you can see what things are important? It looks like My plan is to undo merging this PR, then go from there and see if I can cherry-pick the other edits.

**Comment by Alex-Jordan** [comment]
I was able to fix it all. But I just went 100% with my version of the file. I'll take a close look at your diff and see what things should still be done.

**Comment by Alex-Jordan** [comment]
OK, I think we're good here.

**Comment by aecary** [comment]
Sorry about that. I didn't realize how far you'd gotten. That was the last section I was looking at, and I just hadn't gotten to the last subsection in it.

I'll pull and look through it, but I trust your changes. The main thing with the last subsection was that I'd changed an early Py. Thm. example to have irrational side lengths, which made a later Py. Thm. example redundant.

**Comment by aecary** [comment]
Ok, I looked it over. That looks similar. You grouped the Pyth. Thm. problems, which I agree with. I had commented out the bench example, as it seemed better as an exercise. I don't have a problem with it remaining, and it makes more sense there with the Pyth. Thm. problems grouped.

One note: Line 53 (referring to Py. Thm. problems above that are no longer above) now needs to be cut.

**Comment by Alex-Jordan** [comment]
Great, and I removed that line.

I didn't want to "not interleave" Pythagorean Theorem stuff. But the way things were worded the whole section felt full of nonsequiters. Rather than try to address that directly, I opted to push the Pythagorean stuff down for expediency. And I don't think it was much of a sacrifice in this case.

**Pull request merged**
