### PR TITLE
Prettyprint and permid

### PR DESCRIPTION
**Pull request by davidfarmer**
All ptx files prettyprinted and permids added.

Intended more for discussion than as an official pull request.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Thanks, I'll look carefully later today, possibly tomorrow. I noticed that in frontmatter, there is an "images" element and its "archive" child is not indented.

**Comment by davidfarmer** [comment]
"images" is now prettyprinted.

**Comment by Alex-Jordan** [comment]
Take a look in backmatter.ptx. There is a commented out chunk of XML. Have you thought about pretty-printing commented material like that?

**Comment by Alex-Jordan** [comment]
A few more comments:

1. I think I would prefer the `permid` go at the end of the element. If there are other attributes (`xml:id`, `widths`, etc) these are things the author may need to look at and/or edit. To me, it is easier to do that if they come first. Perhaps to others, that is a reason to put `permid` first. But count me as one data point for preferring it come last.

1. I think I would prefer if the children of a `quantity` were indented on their own line. There are some examples (in general) where so much is going on there with multiple units in numerators and denominators, that separating them out would be useful.

1. `pg-code` appears fine following the pretty-print.

1. The content of a `latex-image` is LaTeX code. Sometimes wrapped in an XML `<![CDATA[...]]>`. That LaTeX code is often structured with `\begin{environment}[options]...\end{environment}`. Can you look at pretty-printing these things as well? ORCCA uses almost exclusively an `axes` environment nested inside a `tikzpicture` environment. Sometimes it is just the latter. There is a simple example at line 92 of `src/section-absolute-value-equations-and-inequalities.ptx`, a more complicated examples at line 180, and a tikz-only example at line 507 of `src/section-geometry-formulas.ptx`. (Line numbers refer to where things land after the current pretty-print.)

1. At line 837 of `src/section-geometry-formulas.ptx`, I do something that may be frowned upon. I put an `aligned` environment with an m tag. There is a reason why, and some day that reason may no longer be a good reason. But forget about that. My request is that if there are line breaks with an m tag, then the pretty print should keep those line breaks (which it does) and indent one more level on each lines (which it currently does not).

Perhaps more later.

**Comment by Alex-Jordan** [comment]
In `rc/section-completing-the-square.ptx` I see a `fact` whose children are not indented.

**Comment by davidfarmer** [comment]
Multiple reply:

I'll indent "fact"s and also add permid.

I am happy to put permid as the last attribute if that is what
people want, or to make it an option to be first or last if
both make sense.

Will everyone want "quantity" to have indented children in all cases?

It is really difficult to modify the inside of comments in a way
that nobody will object to.  What if there are XML fragments (meaning,
tags are unbalanced)?  Even bulk indenting comments is tricky,
which is why I opted to just leave them as-is.

For front matter and backmatter, originally I did not try to
prettyprint that at all, because there are a bunch of one-off
tags and lots of comments.  Also, that material is less likely
to be changed in a pull request, which was the original motivation
for prettyprinting.  Unless there is some general principle
which also applied in the body, I am probably not going to be able
to automate the formatting of those comments.

I'll need to think more about latex-image.  Currently I treat it
as a verbatim environment, meaning that I leave it as-is.  I'll think
about formatting the begin...end subenvironments, but I am not optimistic
that I will find a robust way to do that.

**Comment by Alex-Jordan** [comment]
Possibly helpful:
https://github.com/cmhughes/latexindent.pl

This is Chris Hughes' LaTeX indentation script. Chris (@cmhughes )is formerly of PCC and a WeBWorK contributor. You are using Python, and this script is Perl. But there may be some strategy there for indenting the environments within a `latex-image` element that you could borrow. Or maybe more importantly, Chris may have some warnings about pitfalls he encountered.

**Comment by cmhughes** [comment]
Thanks for this. Happy to help if I can. Latexindent.pl is customizable through its YAML interface.

**Comment by cmhughes** [comment]
Documentation of latexindent at https://latexindentpl.readthedocs.io/en/latest/?badge=latest

**Comment by davidfarmer** [comment]
I updated this pull request by prettyprinting and adding permid to "fact"s,
indenting the content of "quantity", and putting permid as the last attribute.

I don't think I will be able to work on prettyprinting comments or LaTeX in the near future.

**Comment by Alex-Jordan** [comment]
Could you have your script generate a list of tags in this project that do not have a permid? It would help find if there are more things like `fact`.

**Comment by davidfarmer** [comment]
Great idea.  Caught a bug in my code, and also that 'remark',
'list', and 'aside' we not getting permid.  Pull request updated.

Remaining tags that do not have permid:

['abbr', 'acknowledgement', 'acro', 'address', 'alert', 'archive', 
'author', 'c', 'caption', 'cell', 'colophon', 'copyright', 'credit', 
'date', 'description', 'docinfo', 'edition', 'entity', 'foreign', 
'google', 'h', 'holder', 'idx', 'images', 'index', 'init', 'initialism', 
'instruction', 'intertext', 'line', 'm', 'macro-file', 'mag', 'mrow', 
'name', 'notation', 'personname', 'pg-macros', 'pretext', 'pubtitle', 'q', 
'quantity', 'rename', 'role', 'row', 'search', 'see', 'setup', 
'shortlicense', 'stack', 'statement', 'subtitle', 'term', 'title', 
'titlepage', 'todo', 'url', 'usage', 'var', 'website', 'webwork', 'xref', 
'year']

Probably 'stack' should get a permid?  Any others?

**Comment by Alex-Jordan** [comment]
Maybe there should be a forum discussion post about what else needs a permid. Can Rob provide a complete list of all current PTX tags? Some are already categorized as "needs permid". Some are definitely "does not get permid". Then there would be some questions left.

One that I wonder about is "webwork". Suppose I change which source file is a webwork's source attribute. Does that situation just get covered by the parent exercise's permid?

These ones make me wonder: `acknowledgement`, `colophon`, `intertext`, `pretext` (as the replacement for `mathbook`).

**Comment by Alex-Jordan** [comment]
I am gearing up to re-activate the edition branch to work on "edition 2". I will do some light work on that before March, and April through June, we will do more serious revisions as our department reshuffles this curriculum.

So I think it is time to put int he permid~s. Do you want to refresh this PR? Or if you just scrap this one and open a new one. Pull fresh orcca to get an up to date master branch. I just pushed several commits.

**Comment by davidfarmer** [comment]
I pulled from upstream master, re-ran the prettyprinting and permid,
and then pushed to this same pull request.

I paged through the changes and only noticed changes to the permids and
the changes that came when I pulled from master.

**Comment by Alex-Jordan** [comment]
OK, I made fresh HTML so that I can compare outputs before merging this. Checked out your branch immediately ran into a snag when I tried to process the webwork problems. The script turned things like `<image pg-name="$gr" />` into `<image pg-name="$gr" / permid="kqi">` and the slash makes it broken XML.

**Comment by Alex-Jordan** [comment]
GitHub is showing that this PR has conflicts, but I don't understand that. I haven't pushed anything new since 4 days ago. Are you sure you started with the updated source? I looked at one of the conflicts and it is a bit of a head-scratcher. It has your version putting a single WW problem called from the WW server where my version has a lot of PTX-sourced WW problems followed by a few from the server (including  the one yours has).

**Comment by Alex-Jordan** [comment]
If it helps to make the pretty print change things like `<image pg-name="$gr" />` to `<image pg-name="$gr"/>`, that's fine. I was in the habit of using the extra space at the end. When a language has lists (like in XML, a list of attributes) and there is a list separator (like a space in this case) and it is legal in that language, I tend to put a separator after the last item. It can make it more programmable when every list item is followed by a separator. But I'm OK with pretending that is not legal in XML.

**Comment by Alex-Jordan** [comment]
Closing with #457 replacing this.

**Pull request closed without merging**
