### PR TITLE
moved a quadratic application to Math 95 section

### PR DESCRIPTION
**Pull request by caraklee**

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
I'm wondering if everything is here that is supposed to be here. This PR only has one file edited:  src/section-review-of-solving-quadratic-equations.ptx. It has one chunk of content withthe comment `<!-- Moved this example from Math 65 and I'm not sure where it fits best. It would be great for solving graphically with Desmos. -->`.

If this was moved form somewhere, what about the other file that should have the corresponding chunk removed? Was it already handled in an earlier PR?

Also I got the impression from the email thread that maybe there was more you were ready to push. Maybe that was from an earlier PR? Or maybe the knowl deletion error mentioned in that thread was holding you back from pushing?

**Comment by caraklee** [comment]
Yes, that's why I was waiting. Everything is here now.

**Comment by Alex-Jordan** [comment]
Is the "reduced-gravity aircraft" example one that you wrote and are adding for the first time just now? It says it is being moved from somewhere else, but I don't see it being deleted from anywhere. And I searched for that phrase in the repository, but it doesn't come up anywhere.

**Comment by caraklee** [comment]
Yes, I wrote it for 9.3 but then decided it was too complicated for 65 so
it had not been pushed previously. Maybe I should have said "added to 95"
in the comment instead?

*Cara Lee*
Mathematics Instructor
Pronouns: she/her/hers

*Portland Community College*
Southeast Campus, SCOM 214
Phone: 971-722-3773
Email: cara.lee@pcc.edu
Website: www.caraleemath.com

**Comment by Alex-Jordan** [comment]
OK, no problem, that's what I was starting to suspect. I'll merge this now.

**Comment by caraklee** [comment]
Thanks!

*Cara Lee*
Mathematics Instructor
Pronouns: she/her/hers

*Portland Community College*
Southeast Campus, SCOM 214
Phone: 971-722-3773
Email: cara.lee@pcc.edu
Website: www.caraleemath.com

**Pull request merged**
