### PR TITLE
typo

### PR DESCRIPTION
**Pull request by aecary**

### CODE REVIEW

**Comment by aecary** [comment]
Note: I went in and deleted the previous 3 files that the 3 renamed quadratic function sections replace.

**Comment by aecary** [comment]
That very last commit needs to be disregarded. I'm sure there's a way to do this, but I'm not sure how.

**Comment by Alex-Jordan** [comment]
First question: Do you have any subsequent commits right now? 

We should clean this up soon, because it could propagate. And it complicates things if you put more commits on top of it (but still it's OK).

Of course another commit could easily undo this one, but this will be a good exercise. It's not as simple as just leaving out that commit from the merge here, because this commit is still on your machine and on your GitHub repo.

**Comment by aecary** [comment]
I don't have anything that follows that last commit.

I recognized that I could have just re-committed with what it originally
was, but that seemed like the not-best route to go.

*Ann Cary*
(she/her pronouns)
Mathematics Instructor
Curriculum Committee Chair
Portland Community College
Sylvania Campus, ST 203
971-722-7590
<http://goog_233805033>
http://spot.pcc.edu/~acary/

**Comment by Alex-Jordan** [comment]
OK, are you going to be in tomorrow? I could walk you through a git way to handle this. However we do it, this PR needs to be closed, and you need to delete the develop branch from your GitHub repo.

**Comment by aecary** [comment]
Yes, but I have multiple meetings. Can we meet after 3p or before 7:30a?

*Ann Cary*
(she/her pronouns)
Mathematics Instructor
Curriculum Committee Chair
Portland Community College
Sylvania Campus, ST 203
971-722-7590
<http://goog_233805033>
http://spot.pcc.edu/~acary/

**Comment by aecary** [comment]
Otherwise I can change those three numbers back and re-commit so you can
merge it.

*Ann Cary*
(she/her pronouns)
Mathematics Instructor
Curriculum Committee Chair
Portland Community College
Sylvania Campus, ST 203
971-722-7590
<http://goog_233805033>
http://spot.pcc.edu/~acary/

**Comment by Alex-Jordan** [comment]
After 3. But let me try here.

1. `git stash` any unfinished progress.
2. `git log`. Copy the last four commit hashes (the long base16 strings) just so we can check them later.
3. `git rebase -i HEAD~1`
4. Now you are in a text editor where you need to hit `i` to start editing. Delete the word `pick` and replace with a `d`. There are commented out instructions you can read to understand what is happening. After the edit, `ESC`, then `:`, then `x`, then `ENTER` to save and quit.
5. I think that would finish the rebase, but if you get thrown into a second editor, read the instructions and most likely just do `:`, then `x`, then `ENTER` to quit.
6. `git log` should show you the commit hashes from before, minus the one that was dropped.
7. `git stash apply` to bring back stuff from step 2.
8. `git push -f upstream develop`

And that should change this PR.

**Comment by aecary** [comment]
That worked. I double-checked that the commit hash was correct before doing line 8.

**Pull request merged**
